package gui.view;

import DAL.SQLconnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class LoginFormm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFormm
     */
    public LoginFormm() {
        initComponents();
        clearInputs();
    }

    
    private void clearInputs() {
       jTextField_Username.setText("");
       jPasswordField_Password.setText("");
       jCheckBox_ShowPassword.setText("");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jCheckBox_ShowPassword = new javax.swing.JCheckBox();
        jButton_Next = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jPasswordField_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Username");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(70, 100, 110, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Password");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(70, 180, 120, 30);

        jTextField_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UsernameActionPerformed(evt);
            }
        });
        desktopPane.add(jTextField_Username);
        jTextField_Username.setBounds(270, 100, 150, 30);

        jCheckBox_ShowPassword.setText("Show Password");
        jCheckBox_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ShowPasswordActionPerformed(evt);
            }
        });
        desktopPane.add(jCheckBox_ShowPassword);
        jCheckBox_ShowPassword.setBounds(250, 260, 120, 23);

        jButton_Next.setText("Next");
        jButton_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NextActionPerformed(evt);
            }
        });
        desktopPane.add(jButton_Next);
        jButton_Next.setBounds(180, 350, 55, 23);

        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        desktopPane.add(jButton_Cancel);
        jButton_Cancel.setBounds(300, 350, 65, 23);
        desktopPane.add(jPasswordField_Password);
        jPasswordField_Password.setBounds(270, 170, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {                                                    

    }                                                   

    private void jCheckBox_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        if (jCheckBox_ShowPassword.isSelected()){
            jPasswordField_Password.setEchoChar((char)0);
        }else {
            jPasswordField_Password.setEchoChar('*');
        }
    }                                                      

    private void jButton_NextActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Connection con = null;

        try {
            con =  SQLconnector.getConnection() ;
        } catch (SQLException ex) {
            Logger.getLogger(LoginFormm.class.getName()).log(Level.SEVERE, null, ex);
        }
        PreparedStatement ps;
        ResultSet rs;

        try{
            ps = con.prepareStatement("SELECT s FROM Stafi s WHERE s.stafiEmail = :stafiEmail");
            ps.setString(1,jTextField_Username.getName());
            ps.setString(2,String.valueOf(jPasswordField_Password.getPassword()));
            
         

            rs = ps.executeQuery();

            if (rs.next()){

                MainForm mf;
                mf = new MainForm();
                mf.setVisible(true);
                mf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                mf.pack();
                mf.setLocationRelativeTo(null);
                this.dispose();

            }else {

                JOptionPane.showMessageDialog(null,"Invalid Username or Password");

            }
        }   catch (SQLException ex) {
            Logger.getLogger(LoginFormm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {                                               
        clearInputs();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFormm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFormm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Next;
    private javax.swing.JCheckBox jCheckBox_ShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration                   

    
}
