package gui.view;

import BLL.Profesori;
import DAL.BDexception;
import DAL.ProfesoriInterface;
import DAL.ProfesoriRepository;
import gui.model.ProfesoriTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Admin
 */
public class ProfesoriForm extends javax.swing.JInternalFrame {
      ProfesoriInterface pi = new ProfesoriRepository();
    ProfesoriTableModel ptm;
    /**
     * Creates new form ProfesorForm
     */
    public ProfesoriForm() {
        initComponents();
        clearInputs();
    }

    private void clearInputs() {
        Profesori_Id.setText("");
        Profesori_Emri.setText("");
        Profesori_Mbiemri.setText("");
        jDateChooser_DataLindjes.setDate(null);
        Materiali.setText("");
        Telefoni_Profesori.setText("");
    }
    
    
    
    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = ProfessorTable.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {


            @Override
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                  Profesori p;
                    p = ptm.getProfesori (selectedIndex);
                   
        Profesori_Id.setText(p.getProfesoriId() + "");
        Profesori_Emri.setText(p.getProfesoriEmri() + "");
        Profesori_Mbiemri.setText(p.getProfesoriMbiemri() + "");
        jDateChooser_DataLindjes.setDateFormatString(p.getProfesoriDataLindjes());
        Telefoni_Profesori.setText(p.getProfesoriTelefoni() + "");
        Materiali.setText(p.getProfesoriMateriali() + "");
        
                
         }
            }
      });
    }
    
    
    public void tableLoad() {
        try {
            List<Profesori> list;
            list = pi.findAll();
            ptm = new ProfesoriTableModel(list);
             ProfessorTable.setModel(ptm);
            ptm.fireTableDataChanged();        } catch (BDexception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Profesori_Id = new javax.swing.JTextField();
        Profesori_Emri = new javax.swing.JTextField();
        Profesori_Mbiemri = new javax.swing.JTextField();
        jButton_SAVE = new javax.swing.JButton();
        jButton_DELETE = new javax.swing.JButton();
        jButton_CANCEL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProfessorTable = new javax.swing.JTable();
        jDateChooser_DataLindjes = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        Telefoni_Profesori = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Materiali = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 2, 36)); // NOI18N
        jLabel1.setText("       Cloud eLearning");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setText("Emri");

        jLabel4.setText("Mbiemri");

        jLabel6.setText("Data Lindjes");

        jButton_SAVE.setText("SAVE");
        jButton_SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SAVEActionPerformed(evt);
            }
        });

        jButton_DELETE.setText("DELETE");
        jButton_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DELETEActionPerformed(evt);
            }
        });

        jButton_CANCEL.setText("CANCEL");
        jButton_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CANCELActionPerformed(evt);
            }
        });

        ProfessorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Emri", "Mbiemri", "Telefoni", "DataLindjes", "Materiali"
            }
        ));
        jScrollPane1.setViewportView(ProfessorTable);

        jLabel8.setText("Telefoni");

        jLabel5.setText("Materiali");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser_DataLindjes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Profesori_Emri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Profesori_Mbiemri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Profesori_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Telefoni_Profesori)
                            .addComponent(Materiali))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton_DELETE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_CANCEL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Profesori_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Profesori_Emri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Profesori_Mbiemri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser_DataLindjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Telefoni_Profesori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Materiali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_DELETE)
                            .addComponent(jButton_CANCEL)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton_SAVEActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int row ;
        row = ProfessorTable.getSelectedRow();
        if(row == -1){
            Profesori p;
            p = new Profesori();
            
            p.setProfesoriId(Integer.parseInt(Profesori_Id.getText()));
            p.setProfesoriEmri(Profesori_Emri.getText());
            p.setProfesoriMbiemri(Profesori_Mbiemri.getText());
            p.setProfesoriTelefoni( Telefoni_Profesori.getText());
            p.setProfesoriMateriali(Materiali.getText());
            p.setProfesoriDataLindjes(jDateChooser_DataLindjes.getDateFormatString());
            
           

            try {
                pi.create(p);
            } catch (BDexception ex) {
                Logger.getLogger(ProfesoriForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableLoad();
            clearInputs();
        }
        else{
            Profesori p;
            p = new Profesori ();
           
            p.setProfesoriId(Integer.parseInt(Profesori_Id.getText()));
            p.setProfesoriEmri(Profesori_Emri.getText());
            p.setProfesoriMbiemri(Profesori_Mbiemri.getText());
            p.setProfesoriTelefoni( Telefoni_Profesori.getText());
            p.setProfesoriMateriali(Materiali.getText());
            p.setProfesoriDataLindjes(jDateChooser_DataLindjes.getDateFormatString());
            
           
            try {
                pi.create(p);
            } catch (BDexception ex) {
                Logger.getLogger(ProfesoriForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableLoad();
            clearInputs();
        }

    }                                            

    private void jButton_DELETEActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int row ;
        row = ProfessorTable.getSelectedRow();
        if (row != -1){
            Object [] ob = {"Po", "Jo"};
            int result = JOptionPane.showOptionDialog(this," A deshironi ta fshini?", "Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);

            if (result == 0){
                Profesori p;
                p = ptm.getProfesori(row);
                try {
                    pi.remove(p);
                } catch (BDexception se) {
                    JOptionPane.showMessageDialog(this, se.getMessage());
                }
                tableLoad();
            }
            clearInputs();

        } else {
            JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgje per te fshire!");

        }
    }                                              

    private void jButton_CANCELActionPerformed(java.awt.event.ActionEvent evt) {                                               
        clearInputs();
    }                                              


    // Variables declaration - do not modify                     
    private javax.swing.JTextField Materiali;
    private javax.swing.JTextField Profesori_Emri;
    private javax.swing.JTextField Profesori_Id;
    private javax.swing.JTextField Profesori_Mbiemri;
    private javax.swing.JTable ProfessorTable;
    private javax.swing.JTextField Telefoni_Profesori;
    private javax.swing.JButton jButton_CANCEL;
    private javax.swing.JButton jButton_DELETE;
    private javax.swing.JButton jButton_SAVE;
    private com.toedter.calendar.JDateChooser jDateChooser_DataLindjes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   

    
}
